apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portfolio
  template:
    metadata:
      labels:
        app: portfolio
    spec:
      containers:
        - name: kellen-gary-portfolio
          image: kellengary/kellen-gary-portfolio
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: svelte-service
spec:
  selector:
    app: portfolio
  ports:
    - port: 80
      targetPort: 80
